services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U postgres || exit 1
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sample?schema=public
      - REDIS_DB_URL=redis://redis:6379/0
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres-data:
  redis-data: